config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'ror-items', to: 'portfolios#ror'

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tails', to: 'pages#tails'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

  has_many :technologies

  accepts_nested_attributes_for :technologies,
                                reject_if: lambda {|attrs| attrs['name'].blank?}

  validates_presence_of :title, :body, :main_image, :thumb_image

  # scopes - First method - a class method
  def self.angular

    where(subtitle: "Angular")
  end

  # scopes - method - a lambda
  scope :ruby_on_rails_items, -> {where(subtitle: "Ruby on Rails")}

  # When the new action is called
  after_initialize :set_defaults
  #after_create :set_defaults    # not the right spot to set defaults

  def set_defaults
    #self.main_image ||= "https://via.placeholder.com/600x200"
    #self.thumb_image ||= "https://via.placeholder.com/350x200"
    self.main_image ||= Placeholder.image_generator(height: 200, width: 600)
    self.thumb_image ||= Placeholder.image_generator(height: 200, width: 350)
  end

  # Double pipes - Shortcut for
  #if self.main_image == nil
  #  self.main_image = "https://via.placeholder.com/600x200"
  #end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolios"

  def index
    @portfolio_items = Portfolio.all
  end

  def new
    @portfolio_item = Portfolio.new
    3.times {@portfolio_item.technologies.build}
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
    3.times {@portfolio_item.technologies.build}
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was destroyed.' }
    end
  end

  def angular
    @portfolio_items = Portfolio.angular
    render 'index'
  end

  def ror
    @portfolio_items = Portfolio.angular
    @portfolio_items = Portfolio.ruby_on_rails_items
    render 'index'
  end


  private

  # This is just a whitelist
  # Never trust parameters from the scary internet, only allow the white list through.
  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body, 
                                      technologies_attributes: [:name]
                                     )
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <!-- Nested -->
  <ul>
    <%= f.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<p>
  <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %>
</p>
<p>
  <%= portfolio_item.subtitle%>
</p>
<p>
  <%= portfolio_item.body%>
</p>
<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
<%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
<%= link_to 'Destroy', portfolio_path(portfolio_item), method: :delete, data: {confirm: 'Are you sure?'} %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

<%= link_to 'Show', @portfolio_item %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items (<%= @portfolio_items.count %>)</h1>
<%= link_to "Create New Item", new_portfolio_path %>
<br><br><br>

<%= render partial: "portfolio_item", collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create a New Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<h1>Show Portfolio x</h1>

<%= image_tag @portfolio_item.main_image %>

<h1>
  <%= @portfolio_item.title %>
</h1>

<em>
  <%= @portfolio_item.subtitle %>
</em>

<%= @portfolio_item.body %>

<h2>Technologies used:</h2>
<%= @portfolio_item.technologies.each do |t| %>
  <p><%= t.name %></p>
<% end %>


<hr>
<%= params.inspect %>

<%#= session.inspect %>